#!/bin/bash
# Quick CNC Winder Status Check

echo "=== CNC WINDER STATUS ==="
echo "Firmware: $(ls -lh out/klipper.uf2 2>/dev/null | awk '{print $5}' || echo 'Not built')"
echo "Ready to flash: $(test -f out/klipper.uf2 && echo 'YES ✅' || echo 'NO ❌')"
echo "Configuration: $(test -f config/cnc_winder_config.cfg && echo 'OK ✅' || echo 'Missing ❌')"
echo ""
echo "=== QUICK BUILD ==="
echo "Normal build: ./build.sh"
echo "Verbose build: ./build.sh verbose"
echo "Clean build: ./build.sh clean"
echo ""
echo "=== WHAT WARNINGS MEAN ==="
echo "MPU_RBAR_XN_Msk redefined: Normal for RP2350, harmless"
echo "unused functions: Normal, features not implemented yet"
echo "Build time: ~10 seconds"
echo ""
echo "=== NEXT STEPS ==="
echo "1. Flash firmware: cp out/klipper.uf2 /media/*/RPI-RP2/"
echo "2. Setup CM4: ./setup_cnc_winder.sh"
echo "3. Test: Open http://cm4-ip"
