#!/bin/bash
# Explain rsync behavior with examples

CM4_HOST="winder@winder.local"
LOCAL_DIR="klipper-install"
REMOTE_DIR="~/klipper-install"

echo "=========================================="
echo "rsync Behavior Explanation"
echo "=========================================="
echo ""
echo "1. FIRST SYNC (initial copy):"
echo "   - Copies ALL files (first time)"
echo "   - Takes longer, transfers everything"
echo ""
echo "2. SUBSEQUENT SYNCs:"
echo "   - Only copies CHANGED files"
echo "   - Compares: timestamp + file size"
echo "   - Much faster!"
echo ""
echo "3. DRY RUN (-n flag):"
echo "   - Shows what WOULD be copied"
echo "   - Doesn't actually copy anything"
echo "   - Use to preview changes"
echo ""
echo "4. PUSH vs PULL:"
echo "   PUSH (local → CM4):"
echo "     - Overwrites CM4 files with local versions"
echo "     - Use when: local is source of truth"
echo ""
echo "   PULL (CM4 → local):"
echo "     - Overwrites local files with CM4 versions"
echo "     - Use when: CM4 is source of truth"
echo ""
echo "=========================================="
echo "Example: Test with a small change"
echo "=========================================="
echo ""
read -p "Create a test file to demonstrate? [y/N]: " answer

if [ "$answer" = "y" ] || [ "$answer" = "Y" ]; then
    TEST_FILE="$LOCAL_DIR/TEST_RSYNC_DEMO.txt"
    echo "Creating test file: $TEST_FILE"
    echo "Test file created at $(date)" > "$TEST_FILE"
    echo "✓ Created: $TEST_FILE"
    echo ""
    echo "Now run a DRY RUN to see it would be copied:"
    echo "  rsync -avn --exclude='.DS_Store' $LOCAL_DIR/ $CM4_HOST:$REMOTE_DIR/ | grep TEST"
    echo ""
    echo "Then PUSH it:"
    echo "  rsync -av --exclude='.DS_Store' $LOCAL_DIR/ $CM4_HOST:$REMOTE_DIR/"
    echo ""
    echo "Then run DRY RUN again - it won't show up (already synced):"
    echo "  rsync -avn --exclude='.DS_Store' $LOCAL_DIR/ $CM4_HOST:$REMOTE_DIR/ | grep TEST"
    echo ""
    read -p "Delete test file now? [y/N]: " del_answer
    if [ "$del_answer" = "y" ] || [ "$del_answer" = "Y" ]; then
        rm -f "$TEST_FILE"
        echo "✓ Deleted test file"
    fi
fi

echo ""
echo "=========================================="
echo "Quick Commands:"
echo "=========================================="
echo ""
echo "Compare (dry run, see what would change):"
echo "  rsync -avn --exclude='tmp-klipper/' --exclude='klipper-dev/' --exclude='.DS_Store' $LOCAL_DIR/ $CM4_HOST:$REMOTE_DIR/"
echo ""
echo "Push (local → CM4):"
echo "  rsync -av --exclude='tmp-klipper/' --exclude='klipper-dev/' --exclude='.DS_Store' $LOCAL_DIR/ $CM4_HOST:$REMOTE_DIR/"
echo ""
echo "Pull (CM4 → local):"
echo "  rsync -av --exclude='tmp-klipper/' --exclude='klipper-dev/' --exclude='.DS_Store' $CM4_HOST:$REMOTE_DIR/ $LOCAL_DIR/"
echo ""
echo "NOTE: Excludes Klipper source directories (tmp-klipper/, klipper-dev/)"
echo "      These should be cloned separately on each machine."
echo ""
echo "=========================================="

