#!/bin/bash
# List all custom files that need to be added to Klipper installation
# Usage: ./list_custom_files.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "=========================================="
echo "Custom Files for Klipper Installation"
echo "=========================================="
echo ""
echo "These files are NOT in the master Klipper repo"
echo "and must be added to your Klipper installation."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. REQUIRED - Python Modules"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  klippy/extras/winder.py"
echo "    → Winder controller module"
echo "    → Location: $PROJECT_ROOT/klippy/extras/winder.py"
echo ""
echo "  klippy/kinematics/winder.py"
echo "    → Winder kinematics module"
echo "    → Location: $PROJECT_ROOT/klippy/kinematics/winder.py"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "2. RECOMMENDED - Build Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  .config.winder-minimal"
echo "    → Minimal Klipper build config"
echo "    → Location: $PROJECT_ROOT/.config.winder-minimal"
echo "    → Usage: cp .config.winder-minimal .config"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "3. OPTIONAL - Custom Scripts"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  scripts/klipper_interface.py"
echo "    → Python interface to Klipper API"
echo ""
echo "  scripts/simple_stepper_test.py"
echo "    → Basic stepper movement test"
echo ""
echo "  scripts/check_traverse_status.py"
echo "    → Check traverse stepper status"
echo ""
echo "  scripts/diagnose_everything.py"
echo "    → Complete system diagnostic"
echo ""
echo "  scripts/test_winder.py"
echo "    → Comprehensive winder test"
echo ""
echo "  scripts/fix_mcu_shutdown.py"
echo "    → Fix MCU shutdown issues"
echo ""
echo "  scripts/check_winder_logs.py"
echo "    → Filter winder logs"
echo ""
echo "  scripts/diagnose_endstop.py"
echo "    → Diagnose endstop issues"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "4. CORE MODIFICATIONS (Currently None)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Status: ✅ No core modifications"
echo "  See: KLIPPER_CORE_MODIFICATIONS.md"
echo "  Note: PD4 PWM modification was removed (not needed for MP8)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "5. CONFIGURATION FILES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Note: Config files are user-specific and should be copied"
echo "  separately to ~/printer.cfg on your CM4"
echo ""
echo "  Available configs:"
if [ -d "$PROJECT_ROOT/config" ]; then
    ls -1 "$PROJECT_ROOT/config"/*.cfg 2>/dev/null | while read cfg; do
        echo "    → $(basename "$cfg")"
    done || echo "    (No config files found)"
else
    echo "    (config/ directory not found)"
fi
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Quick Copy Commands"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Copy required files:"
echo "cp klippy/extras/winder.py ~/klipper/klippy/extras/"
echo "cp klippy/kinematics/winder.py ~/klipper/klippy/kinematics/"
echo ""
echo "# Copy build config:"
echo "cp .config.winder-minimal ~/klipper/.config"
echo ""
echo "# Or use the script:"
echo "./scripts/add_custom_files_to_klipper.sh ~/klipper"
echo ""

